[package]
name = "neuron600"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["json", "blocking"] }
serde = { version = "1.0", features = ["derive"] }
serde_xml_rs = "0.6"
chrono = "0.4"
