name: Neuron 600 Monitor
on:
  schedule:
    - cron: '*/20 * * * *' 
  workflow_dispatch:      

jobs:
  check-gempa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Run Program
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: cargo run --release
